from enum import Enum


class Stage(str, Enum):
    LOADING = "LOADING"
    PREPROCESSING = "PREPROCESSING"
    SIGNAL_ISOLATION = "SIGNAL_ISOLATION"
    FEATURE_EXTRACTION = "FEATURE_EXTRACTION"
    PARAMETER_ESTIMATION = "PARAMETER_ESTIMATION"
    CANDIDATE_GENERATION = "CANDIDATE_GENERATION"
    CANDIDATE_SCORING = "CANDIDATE_SCORING"
    RE_ESTIMATING = "RE_ESTIMATING"
    BEST_HYPOTHESIS = "BEST_HYPOTHESIS"
    DEINTERLEAVING = "DEINTERLEAVING"
    FEC_DECODING = "FEC_DECODING"
    BITSTREAM_CORRELATION = "BITSTREAM_CORRELATION"
    COMPLETE = "COMPLETE"


STAGE_PROGRESS = {
    Stage.LOADING: 5,
    Stage.PREPROCESSING: 15,
    Stage.SIGNAL_ISOLATION: 25,
    Stage.FEATURE_EXTRACTION: 38,
    Stage.PARAMETER_ESTIMATION: 48,
    Stage.CANDIDATE_GENERATION: 55,
    Stage.CANDIDATE_SCORING: 72,
    Stage.RE_ESTIMATING: 75,
    Stage.BEST_HYPOTHESIS: 82,
    Stage.DEINTERLEAVING: 88,
    Stage.FEC_DECODING: 94,
    Stage.BITSTREAM_CORRELATION: 98,
    Stage.COMPLETE: 100,
}
